export const APP_NAME = 'wii-qare';
export const APP_BASE_PATH = 'api/v1';
export const DOCUMENTATION_PATH = '/api/documentation-v1';
export const JWT_APP_ISSUER = 'WIIQARE';
export const IS_PUBLIC = 'isPublic';
export const ROLES = 'Roles';
export const AUTO_FORGOT_TTL = 180;
export const SALT_ROUNDS = 10;
export const DAY = 1000 * 60 * 60 * 24; // 1 day
export const HOUR = 1000 * 60 * 60; // 1 HOUR
